fireflyPlaidConnector2:
  # "batch" or "polled"
  #   - "batch" runs once, attempting to sync all data up to maxSyncDays, and then exits
  #   - "polled" runs forever, syncing all new data every "syncFrequencyMinutes"
  #     On first run it will attempt to sync all data up to maxSyncDays, if that hasn't already
  #     been done previously and stored in the database.
  syncMode: batch
  syncFrequencyMinutes: 10
  maxSyncDays: 5
  # PlaidTransaction.merchantName will always be used, if available, as the name of a transaction's
  #   destination (or source, for some transfers) account in Firefly.
  # If this is set to true and PlaidTransaction.merchantName is null, then PlaidTransaction.name will
  #   be used instead.
  # If this is set to false and PlaidTransaction.merchantName is null, then the account will be given
  #   a generic "Unknown" name.
  # Defaults to true.
  useNameForDestination: true
  firefly:
#    url: https://firefly.yourdomain.com
#    personalAccessToken: TOKAAAAAN
  plaid:
#    url: https://development.plaid.com
#    clientId: HI I'M A CLIENT ID
#    secret: SECRETZ
    # Transaction categorization configuration (optional, defaults to disable categorization)
    # Plaid currently supplies two types of categorization information https://plaid.com/blog/transactions-categorization-taxonomy/
    # For either categorization type, the provided category strings for a given transaction
    #   will be added as tags to the Firefly transaction using the prefixes below.
    # This is intended to allow you to use Firefly's rule engine to use the tags as triggers to add the transaction to
    #   a budget or category or whatever, rather than trying to squeeze all that logic in here.
    categorization:
      # Add old Plaid categorization information (transaction.category) as tags to Firefly transactions
      # Optional, defaults to disabled.
      old:
        enable: true
        # This value will prefix all Firefly transaction tags populated from old categories.
        # An empty string is a valid value and is the same as omitting this key.
        prefix: "plaid-old-"
        # 'Old' categories are returned in a hierarchical array, with increasing detail farther into the array as per
        #   https://plaid.com/docs/api/products/transactions/#categoriesget
        # This value limits how far into the array we will go when building Firefly transaction tags.
        # For instance, consider a transaction with old categories:
        #   "TRANSFER", "THIRD_PARTY", "PAYPAL"
        # With depthLimit set to 1, the Firefly transaction tag would be ${prefix}TRANSFER
        # With depthLimit set to 2, the Firefly transaction tag would be ${prefix}TRANSFER-THIRD_PARTY
        # With depthLimit set to 3 or greater, the Firefly transaction tag would be ${prefix}TRANSFER-THIRD_PARTY-PAYPAL
        #   (I don't think a depth higher than 3 is possible, for what it's worth)
        # Optional, defaults to 3
        depthLimit: 3
      # Use new Plaid categorization information (transaction.personalFinanceCategory)
      # Optional, defaults to disabled.
      new:
        primary:
          enable: true
          prefix: "plaid-new-primary-"
        detailed:
          enable: true
          prefix: "plaid-new-detailed-"
  # An array of accounts to sync from Plaid to Firefly
  accounts:
      # The account id in Firefly to sync this data to.
      # For instance, an account you view at https://localhost/accounts/show/1 will be id 1
#    - fireflyAccountId: 1
      # The access token for the Plaid item that contains the account
      # You can set up Plaid Items using Plaid Quickstart https://github.com/plaid/quickstart
      # Note that Items can contain multiple Accounts, so you may re-use this access token in
      #   other entries in this YAML array
#      plaidItemAccessToken: access-development-insert-uuid-here
      # The Plaid id for the account you want to sync.
      # You can retrieve this id from https://plaid.com/docs/api/accounts/#accountsget using an
      #   Item's access token after you've set it up.
#      plaidAccountId: omgwtfbbq
  product:
    name: Firefly Plaid Connector 2
