fireflyPlaidConnector2:
  # "batch" or "polled"
  #   - "batch" runs once, attempting to sync all data up to maxSyncDays, and then exits
  #   - "polled" runs forever, syncing all new data every "syncFrequencyMinutes"
  #     On first run it will attempt to sync all data up to maxSyncDays, if that hasn't already
  #     been done previously and stored in the database.
  syncMode: batch
  syncFrequencyMinutes: 10
  maxSyncDays: 5
  # PlaidTransaction.merchantName will always be used, if available, as the name of a transaction's
  #   destination (or source, for some transfers) account in Firefly.
  # If this is set to true and PlaidTransaction.merchantName is null, then PlaidTransaction.name will
  #   be used instead.
  # If this is set to false and PlaidTransaction.merchantName is null, then the account will be given
  #   a generic "Unknown" name.
  # Defaults to true.
  useNameForDestination: true
  firefly:
#    url: https://firefly.yourdomain.com
#    personalAccessToken: TOKAAAAAN
  plaid:
#    url: https://development.plaid.com
#    clientId: HI I'M A CLIENT ID
#    secret: SECRETZ
  # Transaction categorization configuration (optional, defaults to disable categorization)
  # Plaid currently supplies two types of categorization information https://plaid.com/blog/transactions-categorization-taxonomy/
  # The current plan is to ignore the old categorization type because the new type (transaction.personalFinanceCategory)
  #   is fully rolled out and seems superior across the board.
  # If categorization is enabled, the category strings provided by Plaid for a given transaction
  #   will be added as tags to the Firefly transaction using the prefixes below.
  # This is intended to allow you to use Firefly's rule engine to use the tags as triggers to add the transaction to
  #   a budget or category or whatever, rather than trying to squeeze all that logic in here.
  # See https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv for a list of categories
  categorization:
    # Controls tagging for a Plaid transaction's primary personal finance category
    # If enabled, the prefix below will be used to create a tag with the transaction's primary personal finance category.
    # For instance, consider a transaction with primary category INCOME.
    #   With the default prefix, that transaction would be tagged in Firefly with "plaid-primary-cat-income"
    # Optional, defaults to disabled
    primary:
      # Set to true to enable tags for a Plaid transaction's primary personal finance category
      # Optional, defaults to false
      enable: true
      # Optional, defaults to "plaid-primary-cat-"
      prefix: "plaid-primary-cat-"
    # Controls tagging for a Plaid transaction's detailed personal finance category
    # Same as primary above, but using the detailed personal finance category field.
    # For instance, consider a transaction with detailed category INCOME_DIVIDENDS.
    #   With the default prefix, that transaction would be tagged in Firefly with "plaid-detailed-cat-dividends"
    # Optional, defaults to disabled
    detailed:
      # Set to true to enable tags for a Plaid transaction's detailed personal finance category
      # Optional, defaults to false
      enable: true
      # Optional, defaults to "plaid-detailed-cat-"
      prefix: "plaid-detailed-cat-"
  # An array of accounts to sync from Plaid to Firefly
  accounts:
      # The account id in Firefly to sync this data to.
      # For instance, an account you view at https://localhost/accounts/show/1 will be id 1
#    - fireflyAccountId: 1
      # The access token for the Plaid item that contains the account
      # You can set up Plaid Items using Plaid Quickstart https://github.com/plaid/quickstart
      # Note that Items can contain multiple Accounts, so you may re-use this access token in
      #   other entries in this YAML array
#      plaidItemAccessToken: access-development-insert-uuid-here
      # The Plaid id for the account you want to sync.
      # You can retrieve this id from https://plaid.com/docs/api/accounts/#accountsget using an
      #   Item's access token after you've set it up.
#      plaidAccountId: omgwtfbbq
  product:
    name: Firefly Plaid Connector 2
